#!!! Start your miner using the following command ([address] replace with your wallet) !!!!
#Hush https://coorp.io/coins/hush - Hush
./miner --server us.coorp.io --user t1RGwDc21mxd9J511GkQng78j8aFrZPJa3A.workerName --pass x --port 3034
#https://coorp.io/coins/vot - Votecoin
#miner --server us.coorp.io --user t1MskC7ubCKUDixmbYL7cLHvdkNJg5aDXpd.workerName --pass x --port 3035
#https://coorp.io/coins/btcz - BitcoinZ
#miner --server us.coorp.io --user t1gUFb4za5jLvpjz7iRc3hPPcFySMdtkKYv.workerName --pass x --port 3033
#https://coorp.io/coins/sng SnowGem
#miner --server us.coorp.io --user [address].[worker] --pass x --port 3031
#https://coorp.io/coins/kmd
#miner --server eu.coorp.io --user RSCMuFshgvVnf6X4ukVgBHv9zS1sUdr2Ld.workerName --pass x --port 3857